{
 "title": "MergeStat Examples",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repositories",
    "label": "Repositories",
    "query": "SELECT owner || '/' || name FROM github_repo_info JOIN repos ON github_repo_info.repo_id = repos.id"
   },
   {
    "name": "repository_tags",
    "label": "Repository Tags",
    "query": "SELECT DISTINCT value FROM repos, jsonb_array_elements_text(tags) "
   },
   { "name": "interval", "label": "Interval", "query": "1d,7d,14d,30d,90d,180d" },
   {
    "name": "state",
    "label": "Issue State",
    "query": "SELECT DISTINCT state FROM public.github_issues"
   },
   {
    "name": "labels",
    "label": "Issue Labels",
    "query": "SELECT DISTINCT JSONB_ARRAY_ELEMENTS_TEXT(public.github_issues.labels) AS label FROM public.github_issues order by 1"
   }
  ]
 },
 "panels": [
  { "title": "Pull Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PRs Merged in Period",
   "type": "stat",
   "description": "Number of PRs merged in period",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE $__timeFilter(merged_at)\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? base_repository_name) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Across This Many Repos",
   "type": "stat",
   "description": "Number of repositories that had PRs merged",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT repo_id) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE $__timeFilter(merged_at)\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? base_repository_name) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Unique PR Authors",
   "type": "stat",
   "description": "Number of PR authors in period",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT author_login) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE $__timeFilter(merged_at)\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? base_repository_name) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "PRs Merged by Repository",
   "type": "piechart",
   "description": "Count of PRs merged within time period for matching repositories",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT base_repository_name, count(*) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged AND $__timeFilter(merged_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? base_repository_name) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY base_repository_name ORDER BY count(*) DESC"
    }
   ]
  },
  {
   "title": "PRs by Repo (by ${interval})",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*),\n\tbase_repository_name,\n\t$__timeGroup(merged_at, '${interval}', 0) AS time\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at)\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? base_repository_name) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time"
    }
   ]
  },
  { "title": "Stargazers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Stargazers by Repo (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*),\n\t(public.github_repo_info.owner || '/' || public.github_repo_info.name) AS base_repository_name,\n\t$__timeGroup(starred_at, '${interval}', 0) AS time\nFROM public.github_stargazers\nINNER JOIN public.github_repo_info ON public.github_stargazers.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nWHERE starred_at IS NOT NULL\nAND $__timeFilter(public.github_stargazers.starred_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  { "title": "Tags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Tags by Repo  (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    'Total Tags' AS base_repository_name,\n    $__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time,\n    COUNT(*) AS total_tags\nFROM public.git_refs\nINNER JOIN public.git_commits ON public.git_refs.tag_commit_hash = public.git_commits.hash AND public.git_refs.repo_id = public.git_commits.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nWHERE\n    public.git_refs.type = 'tag'\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time, total_tags"
    },
    {
     "rawSql": "SELECT\n    public.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n    $__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time,\n    COUNT(*) AS total_tags\nFROM public.git_refs\nINNER JOIN public.git_commits ON public.git_refs.tag_commit_hash = public.git_commits.hash AND public.git_refs.repo_id = public.git_commits.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nWHERE\n    public.git_refs.type = 'tag'\nAND $__timeFilter(public.git_commits.committer_when)\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time, total_tags"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Issues Created by Repo (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) AS total_issues,\n    public.repos.repo,\n    $__timeGroup(public.github_issues.created_at, '${interval}', 0) AS time\nFROM public.github_issues\nINNER JOIN public.github_repo_info ON public.github_issues.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nWHERE public.github_issues.created_at IS NOT NULL\nAND $__timeFilter(public.github_issues.created_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${state:json}'::jsonb) <> 0 THEN ('${state:json}'::jsonb ? public.github_issues.state) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${labels:json}'::jsonb) <> 0 THEN (public.github_issues.labels @> '${labels:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "Issues Created Labels (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "WITH labels AS (SELECT\n        public.github_issues.database_id,\n        public.github_issues.repo_id,\n        JSONB_ARRAY_ELEMENTS_TEXT(public.github_issues.labels) AS label\n    FROM public.github_issues\n)\n\nSELECT\n    COUNT(*) AS total_issues,\n    labels.label,\n    $__timeGroup(public.github_issues.created_at, '${interval}', 0) AS time\nFROM public.github_issues\nINNER JOIN labels ON public.github_issues.repo_id = labels.repo_id AND public.github_issues.database_id = labels.database_id\nINNER JOIN public.github_repo_info ON public.github_issues.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nWHERE public.github_issues.created_at IS NOT NULL\nAND $__timeFilter(public.github_issues.created_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${state:json}'::jsonb) <> 0 THEN ('${state:json}'::jsonb ? public.github_issues.state) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${labels:json}'::jsonb) <> 0 THEN (public.github_issues.labels @> '${labels:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  { "title": "Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Commits by Repo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT public.git_commits.hash) as count,\n\t'Total Commits' AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when)\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time, count"
    },
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT public.git_commits.hash) as count,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when)\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time, count"
    }
   ]
  },
  { "title": "Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Total Workflows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) AS total_worfkflows\nFROM public.git_files\nINNER JOIN public.repos ON public.repos.id = public.git_files.repo_id\nWHERE public.git_files.path LIKE '.github/workflows%.y%ml'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Go Versions by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n    dependencies_go_version,\n    SUM(count) AS count\nFROM (SELECT\n    1 AS count,\n    SUBSTRING(public.git_files.contents FROM 'go ([0-9]+.[0-9]+)') AS dependencies_go_version\n    FROM public.git_files\n    INNER JOIN public.repos ON public.repos.id = public.git_files.repo_id\n    WHERE public.git_files.path LIKE '%go.mod'\n) AS t\nGROUP BY dependencies_go_version\n"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n    public.repos.repo AS repo,\n    public.git_files.path\nFROM public.git_files\nINNER JOIN public.repos ON public.repos.id = public.git_files.repo_id\nWHERE public.git_files.path LIKE '.github/workflows%.y%ml' --Allows for both .yml and .yaml\nORDER BY 1"
    }
   ]
  },
  {
   "title": "React Locked Versions by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n    dependencies_react_version,\n    SUM(count) as count\nFROM (SELECT\n    public.repos.repo,\n    COALESCE(\n        JSON_EXTRACT_PATH_TEXT(public.git_files.contents::json, variadic '{packages,\"\",dependencies,react}'), --additional paths can be added to this coalesce statement\n        JSON_EXTRACT_PATH_TEXT(public.git_files.contents::json, variadic '{dependencies,react,version}'),\n        ''\n    ) AS dependencies_react_version,\n    1 AS count\n    FROM public.git_files\n    INNER JOIN public.repos ON public.repos.id = public.git_files.repo_id\n    WHERE public.git_files.path LIKE '%package-lock.json' AND public.git_files.contents LIKE '%\"react\"%'\n) AS t\nGROUP BY dependencies_react_version\n"
    }
   ]
  },
  { "title": "Trivy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Total Critical Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) AS total_vulnerabilities\nFROM public.trivy_repo_vulnerabilities\nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nINNER JOIN public.github_repo_info ON public.trivy_repo_vulnerabilities.repo_id = public.github_repo_info.repo_id\nWHERE public.trivy_repo_vulnerabilities.vulnerability_severity = 'CRITICAL'\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\n"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Repo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    public.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n    COUNT(case when (vulnerability_severity='UNKNOWN') then 1 else NULL end) as unknown,\n    COUNT(case when (vulnerability_severity='LOW') then 1 else NULL end) as low,\n    COUNT(case when (vulnerability_severity='MEDIUM') then 1 else NULL end) as medium,\n    COUNT(case when (vulnerability_severity='HIGH') then 1 else NULL end) as high,\n    COUNT(case when (vulnerability_severity='CRITICAL') then 1 else NULL end) as critical,\n    COUNT(*) AS total_vulnerabilities\nFROM public.trivy_repo_vulnerabilities\nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nINNER JOIN public.github_repo_info ON public.trivy_repo_vulnerabilities.repo_id = public.github_repo_info.repo_id\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 1\nORDER BY 7 DESC\n"
    }
   ]
  },
  {
   "title": "Critical Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT\n    (public.github_repo_info.owner || '/' || public.github_repo_info.name) as repo,\n    public.trivy_repo_vulnerabilities.vulnerability_id,\n    public.trivy_repo_vulnerabilities.vulnerability_title,\n    JSON_EXTRACT_PATH_TEXT(public.trivy_repo_vulnerabilities.vulnerability::json, variadic '{PublishedDate}') AS PublishedDate,\n    JSON_EXTRACT_PATH_TEXT(public.trivy_repo_vulnerabilities.vulnerability::json, variadic '{FixedVersion}') AS FixedVersion,\n    public.trivy_repo_vulnerabilities.vulnerability_installed_version\nFROM public.trivy_repo_vulnerabilities\nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nINNER JOIN public.github_repo_info ON public.trivy_repo_vulnerabilities.repo_id = public.github_repo_info.repo_id\nWHERE public.trivy_repo_vulnerabilities.vulnerability_severity = 'CRITICAL'\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nORDER BY 1"
    }
   ]
  }
 ]
}