BEGIN;

-- Setup the mergestat_admin role
GRANT USAGE ON SCHEMA sqlq TO mergestat_admin WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sqlq TO mergestat_admin WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT ALL PRIVILEGES ON TABLES TO mergestat_admin WITH GRANT OPTION;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA sqlq TO mergestat_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT USAGE ON SEQUENCES TO mergestat_admin;

-- Setup the mergestat_role_admin role
GRANT USAGE ON SCHEMA sqlq TO mergestat_role_admin WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sqlq TO mergestat_role_admin WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT ALL PRIVILEGES ON TABLES TO mergestat_role_admin WITH GRANT OPTION;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA sqlq TO mergestat_role_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT USAGE ON SEQUENCES TO mergestat_role_admin;

-- Setup the mergestat_role_user role
GRANT USAGE ON SCHEMA sqlq TO mergestat_role_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sqlq TO mergestat_role_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mergestat_role_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA sqlq TO mergestat_role_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT USAGE ON SEQUENCES TO mergestat_role_user;

-- Setup the mergestat_role_readonly role
GRANT USAGE ON SCHEMA sqlq TO mergestat_role_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA sqlq TO mergestat_role_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT SELECT ON TABLES TO mergestat_role_readonly;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA sqlq TO mergestat_role_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA sqlq GRANT USAGE ON SEQUENCES TO mergestat_role_readonly;

COMMIT;
