{
 "title": "OSV Scan Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repositories",
    "label": "OSV Scanned Repositories",
    "query": "SELECT repo FROM repos\nRIGHT JOIN osv_repo_scans ON repos.id = osv_repo_scans.repo_id\nORDER BY repo"
   }
  ]
 },
 "panels": [
  { "title": "CVE Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM osv_vulnerabilities\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repo)) ELSE true END)\n"
    }
   ]
  },
  {
   "title": "Vulnerability Count by Age (in Days)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH vuln_age AS (\n    SELECT round(EXTRACT(epoch FROM (SELECT (now() - published)))/86400, 2) AS avg_age_days, id FROM osv_vulnerabilities\n    WHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repo)) ELSE true END)\n)\nSELECT floor(avg_age_days/30)*30 AS age_days_floor, count(*)\n    FROM vuln_age\n    GROUP BY 1\n    ORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Vulnerability Count by Severity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(sev, 'UNKNOWN') AS sev, count(*) FROM osv_vulnerabilities\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repo)) ELSE true END)\nGROUP BY sev\nORDER BY CASE\n    WHEN sev='CRITICAL' THEN 1\n    WHEN sev='HIGH' THEN 2\n    WHEN sev='MODERATE' THEN 3\n    WHEN sev='LOW' THEN 4\n    ELSE 5\nEND\n"
    }
   ]
  },
  {
   "title": "Vulnerability Count by Ecosystem",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT pkg_ecosystem, count(*) FROM osv_vulnerabilities\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repo)) ELSE true END)\nGROUP BY pkg_ecosystem\nORDER BY count(*) DESC\n"
    }
   ]
  },
  {
   "title": "Avg (mean) Age of Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(EXTRACT(epoch FROM (SELECT (avg(now() - published))))/86400, 2) AS avg_age_days FROM osv_vulnerabilities\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repo)) ELSE true END)\n"
    }
   ]
  },
  { "title": "CVE Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Vulnerabilities by Repo (Top 10)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    repo,\n    COUNT(case when (sev='LOW') then 1 else NULL end) as low,\n    COUNT(case when (sev='MODERATE') then 1 else NULL end) as moderate,\n    COUNT(case when (sev='HIGH') then 1 else NULL end) as high,\n    COUNT(case when (sev='CRITICAL') then 1 else NULL end) as critical,\n    COUNT(case when (sev is null) then 1 else null end) as unknown,\n    COUNT(*) AS total_vulnerabilities\nFROM public.osv_vulnerabilities\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repo)) ELSE true END)\nGROUP BY 1\nORDER BY total_vulnerabilities DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "All Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT repo, pkg_ecosystem, pkg_name, pkg_version, sev, id, details, published FROM osv_vulnerabilities\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repo)) ELSE true END)"
    }
   ]
  }
 ]
}