{
 "title": "Pull Requests",
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "templating": {
  "list": [
   {
    "name": "repositories",
    "label": "Repositories",
    "query": "SELECT owner || '/' || name FROM github_repo_info JOIN repos ON github_repo_info.repo_id = repos.id"
   },
   {
    "name": "repository_tags",
    "label": "Repository Tags",
    "query": "SELECT DISTINCT value FROM repos, jsonb_array_elements_text(tags) "
   },
   { "name": "interval", "label": "Interval", "query": "1d,7d,14d,30d,90d,180d" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PRs Merged in Period",
   "type": "stat",
   "description": "Number of PRs merged in period",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Across This Many Repos",
   "type": "stat",
   "description": "Number of repositories that had PRs merged",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT repo_id) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Unique PR Authors",
   "type": "stat",
   "description": "Number of PR authors in period",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT author_login) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "PRs Merged by Repository",
   "type": "piechart",
   "description": "Count of PRs merged within time period for matching repositories",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT base_repository_name, count(*) FROM github_pull_requests\nJOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged AND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY base_repository_name ORDER BY count(*) DESC"
    }
   ]
  },
  {
   "title": "PRs by Repo (by ${interval})",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*),\n\tbase_repository_name,\n\t$__timeGroup(merged_at, '${interval}', 0) AS time\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Time To Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean Time To Merge for Period",
   "type": "stat",
   "description": "The average (mean) duration between a PR creation and merge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tAVG(EXTRACT(EPOCH FROM github_pull_requests.merged_at - github_pull_requests.created_at)) AS time_to_merge\nFROM github_pull_requests\nJOIN repos ON (repos.id = github_pull_requests.repo_id)\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "p95 Time To Merge",
   "type": "stat",
   "description": "95th percentile of time to merge of selected PRs",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_disc(0.95) WITHIN GROUP (ORDER BY time_to_merge) as p95 FROM (\n  SELECT\n  \tEXTRACT(EPOCH FROM github_pull_requests.merged_at - github_pull_requests.created_at) AS time_to_merge\n  FROM github_pull_requests JOIN repos ON (github_pull_requests.repo_id = repos.id)\n  WHERE merged_at IS NOT NULL\n  AND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\n  AND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\n) AS prs"
    }
   ]
  },
  {
   "title": "Distribution of Time To Merge",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(EPOCH FROM github_pull_requests.merged_at - github_pull_requests.created_at) / 3600 AS time_to_merge\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Mean Time To Merge (per ${interval})",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(merged_at, '${interval}', 0) AS time,\n\tAVG(EXTRACT(EPOCH FROM github_pull_requests.merged_at - github_pull_requests.created_at)) AS time_to_merge\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Mean Time To Merge by Repo (per ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(merged_at, '${interval}', 0) AS time,\n\tAVG(EXTRACT(EPOCH FROM github_pull_requests.merged_at - github_pull_requests.created_at)) AS time_to_merge,\n\tbase_repository_name\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg. Additions",
   "type": "stat",
   "description": "The average (mean) number of lines added by a PR",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Lines" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tAVG(additions)\nFROM github_pull_requests\nJOIN repos ON (repos.id = github_pull_requests.repo_id)\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Avg. Deletions",
   "type": "stat",
   "description": "The average (mean) number of lines removed by a PR",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Lines" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tAVG(deletions)\nFROM github_pull_requests\nJOIN repos ON (repos.id = github_pull_requests.repo_id)\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Avg. Files Modified",
   "type": "stat",
   "description": "The average (mean) number of files modified by a PR",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Files" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tAVG(changed_files)\nFROM github_pull_requests\nJOIN repos ON (repos.id = github_pull_requests.repo_id)\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "Avg. Files Modified (per ${interval})",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "FIles" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(merged_at, '${interval}', 0) AS time,\n\tAVG(changed_files)\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged_at IS NOT NULL\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Risks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PRs Merged Without Review",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged AND review_decision <> 'APPROVED'\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "PRs Merged Without Review",
   "type": "table",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT base_repository_name, author_login, title, url, merged_at FROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged AND review_decision <> 'APPROVED'\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nORDER BY merged_at DESC"
    }
   ]
  },
  {
   "title": "PRs Merged Without Review (by Repo)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*), base_repository_name FROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE merged AND review_decision <> 'APPROVED'\nAND $__timeFilter(merged_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY base_repository_name\nORDER BY count(*) DESC"
    }
   ]
  },
  {
   "title": "PRs Open More than 5 Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE NOT merged AND state = 'OPEN'\nAND (now() - github_pull_requests.created_at) > '5 days'::interval\nAND $__timeFilter(github_pull_requests.created_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)"
    }
   ]
  },
  {
   "title": "PRs Open for More Than 5 Days",
   "type": "table",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 83 },
   "targets": [
    {
     "rawSql": "SELECT\n  base_repository_name,\n  now() - github_pull_requests.created_at AS time_open,\n  author_login,\n  title,\n  url,\n  github_pull_requests.created_at\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE NOT merged AND state = 'OPEN'\nAND (now() - github_pull_requests.created_at) > '5 days'::interval\nAND $__timeFilter(github_pull_requests.created_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nORDER BY time_open DESC"
    }
   ]
  },
  {
   "title": "PRs Opens More than 5 Days by Repo",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*), base_repository_name\nFROM github_pull_requests JOIN repos ON github_pull_requests.repo_id = repos.id\nWHERE NOT merged AND state = 'OPEN'\nAND (now() - github_pull_requests.created_at) > '5 days'::interval\nAND $__timeFilter(github_pull_requests.created_at) AND '${repositories:json}'::jsonb ? base_repository_name\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY base_repository_name\nORDER BY count(*) DESC"
    }
   ]
  },
  { "title": "Day of Week", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Pull Requests By Day of Week",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    EXTRACT(DOW FROM public.github_pull_requests.created_at) AS day_of_week_num,\n    TO_CHAR(public.github_pull_requests.created_at, 'Day') AS day_of_week,\n    COUNT(*) AS total_pull_requests\nFROM public.github_pull_requests\nINNER JOIN public.github_repo_info ON public.github_pull_requests.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_pull_requests.repo_id = public.repos.id\nAND $__timeFilter(public.github_pull_requests.created_at) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pull Requests By Repo By Day of Week",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (public.github_repo_info.owner || '/' || public.github_repo_info.name),\n    EXTRACT(DOW FROM public.github_pull_requests.created_at) AS day_of_week_num,\n    TO_CHAR(public.github_pull_requests.created_at, 'Day') AS day_of_week,\n    COUNT(*) AS total_pull_requests\nFROM public.github_pull_requests\nINNER JOIN public.github_repo_info ON public.github_pull_requests.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_pull_requests.repo_id = public.repos.id\nAND $__timeFilter(public.github_pull_requests.created_at) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 1,2,3\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Pull Requests By Author By Day of Week",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    public.github_pull_requests.author_name,\n    EXTRACT(DOW FROM public.github_pull_requests.created_at) AS day_of_week_num,\n    TO_CHAR(public.github_pull_requests.created_at, 'Day') AS day_of_week,\n    COUNT(*) AS total_pull_requests\nFROM public.github_pull_requests\nINNER JOIN public.github_repo_info ON public.github_pull_requests.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_pull_requests.repo_id = public.repos.id\nAND $__timeFilter(public.github_pull_requests.created_at) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 1,2,3\nORDER BY 1,2"
    }
   ]
  }
 ]
}