{
 "title": "Fuse Management",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Rows Synced",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH tbl AS (SELECT\n    table_schema,\n    table_name\n    FROM information_schema.tables\n    WHERE table_name NOT LIKE 'pg_%'\n        AND table_schema IN ('public')\n        AND table_name != 'schema_migrations'\n)\n\nSELECT SUM(count) as count from\n(SELECT\n    table_schema,\n    table_name,\n    (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from %I.%I', table_schema, table_name), FALSE, TRUE, '')))[1]::text::int AS count\nFROM tbl\n) tbl2"
    }
   ]
  },
  {
   "title": "Total Repo Syncs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS total_repo_syncs\nFROM mergestat.repo_syncs\n"
    }
   ]
  },
  {
   "title": "Total Syncs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_syncs\nFROM mergestat.repo_sync_queue"
    }
   ]
  },
  {
   "title": "Total Repos With No Sync Types",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(count) AS total_repos_with_no_syncs\nFROM\n    (\n        SELECT\n            public.repos.repo,\n            COUNT(repo_syncs.sync_type) AS count\n        FROM public.repos\n        INNER JOIN mergestat.repo_syncs ON public.repos.id = mergestat.repo_syncs.repo_id\n        GROUP BY 1\n        HAVING COUNT(repo_syncs.sync_type) = 0\n    ) AS t\n"
    }
   ]
  },
  { "title": "Row Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Row Count All Tables",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH tbl AS (SELECT\n    table_schema,\n    table_name\n    FROM information_schema.tables\n    WHERE table_name NOT LIKE 'pg_%'\n        AND table_schema IN ('public', 'mergestat')\n        AND table_name != 'schema_migrations'\n)\n\nSELECT\n    table_schema,\n    table_name,\n    (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from %I.%I', table_schema, table_name), FALSE, TRUE, '')))[1]::text::int AS count\nFROM tbl\nORDER BY 1 DESC, 3 DESC\n"
    }
   ]
  },
  {
   "title": "Row Count by Repo",
   "type": "table",
   "description": "Only includes tables that contain a repo_id column",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH tbl AS (SELECT\n    information_schema.tables.table_schema,\n    information_schema.tables.table_name\n    FROM information_schema.tables\n    JOIN information_schema.columns ON information_schema.columns.table_name = information_schema.tables.table_name AND information_schema.columns.table_schema = information_schema.tables.table_schema\n    WHERE information_schema.tables.table_name NOT LIKE 'pg_%'\n        AND information_schema.tables.table_schema IN ('public', 'mergestat')\n        AND information_schema.columns.column_name = 'repo_id'\n)\n\nSELECT\n    table_schema,\n    table_name,\n    public.repos.repo,\n    (xpath('/row/c/text()', query_to_xml(format('SELECT COUNT(*) AS c FROM %I.%I JOIN public.repos ON public.repos.id = %I.%I.repo_id WHERE public.repos.id = ''%s''' , table_schema, table_name, table_schema, table_name, public.repos.id), FALSE, TRUE, '')))[1]::text::int AS count\nFROM tbl CROSS JOIN public.repos\nORDER BY 1 DESC, 2 DESC, 4 DESC\n"
    }
   ]
  },
  { "title": "Sync Types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Sync Types by Repo",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n    public.repos.repo,\n    COUNT(repo_syncs.sync_type)\nFROM public.repos\nINNER JOIN mergestat.repo_syncs ON public.repos.id = mergestat.repo_syncs.repo_id\nGROUP BY 1\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Sync Types by Repo",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \n    public.repos.repo,\n    repo_syncs.sync_type\nFROM public.repos\nJOIN mergestat.repo_syncs ON public.repos.id = mergestat.repo_syncs.repo_id\nORDER BY 1, 2"
    }
   ]
  }
 ]
}