{
 "title": "TODO Comments",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Total TODOs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS \"value\"\nFROM git_blame\nWHERE\n  $__timeFilter(author_when)\n  AND line LIKE '%TODO%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Repos",
   "type": "stat",
   "description": "Repositories where TODO comments have been found",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(DISTINCT repos.repo)\nFROM git_blame\nJOIN repos ON repos.id = repo_id\nWHERE\n  $__timeFilter(author_when)\nAND line LIKE '%TODO%'\nORDER BY count(*) DESC"
    }
   ]
  },
  {
   "title": "Average (Mean) Age in Days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(extract(EPOCH FROM (now() - author_when))::integer/60/60/24) AS age\nFROM git_blame\nJOIN repos ON repos.id = repo_id\nWHERE\n  $__timeFilter(author_when)\nAND line LIKE '%TODO%'"
    }
   ]
  },
  {
   "title": "Avg. Age of a TODO Comment by Author",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(now() - git_blame.author_when) AS age,\n  author_name\nFROM git_blame\nJOIN repos ON repos.id = repo_id\nWHERE\n  $__timeFilter(author_when)\nAND line LIKE '%TODO%'\nGROUP BY author_name\nORDER BY age ASC"
    }
   ]
  },
  {
   "title": "TODOs by Repo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  REPLACE(repos.repo, 'https://github.com/', '') AS repo,\n  count(*)\nFROM git_blame\nJOIN repos ON repos.id = repo_id\nWHERE\n  $__timeFilter(author_when)\nAND line LIKE '%TODO%'\nGROUP BY repo\nORDER BY count(*) DESC"
    }
   ]
  },
  {
   "title": "TODOs by Author",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  author_name,\n  count(*)\nFROM git_blame\nJOIN repos ON repos.id = repo_id\nWHERE\n  $__timeFilter(author_when)\nAND line LIKE '%TODO%'\nGROUP BY author_name\nORDER BY count(*) DESC"
    }
   ]
  },
  {
   "title": "TODO List",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  REPLACE(repos.repo, 'https://github.com/', ''),\n  git_blame.line,\n  repos.repo || '/blob/main/' || git_blame.path || '#L' || git_blame.line_no AS url,\n  git_blame.author_name,\n  git_blame.author_email,\n  git_blame.author_when\nFROM git_blame\nJOIN repos ON repos.id = repo_id\nWHERE\n  $__timeFilter(author_when)\nAND line LIKE '%TODO%'\nORDER BY git_blame.author_when ASC\n"
    }
   ]
  }
 ]
}