{
 "title": "Commits",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repositories",
    "label": "Repositories",
    "query": "SELECT owner || '/' || name FROM github_repo_info JOIN repos ON github_repo_info.repo_id = repos.id"
   },
   {
    "name": "repository_tags",
    "label": "Repository Tags",
    "query": "SELECT DISTINCT value FROM repos, jsonb_array_elements_text(tags) "
   },
   { "name": "interval", "label": "Interval", "query": "1d,7d,14d,30d,90d,180d" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commits by Repo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT public.git_commits.hash) as count,\n\t'Total Commits' AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time, count"
    },
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT public.git_commits.hash) as count,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY time, base_repository_name\nORDER BY time, count"
    }
   ]
  },
  {
   "title": "Commits by Day of Week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(*) as count,\n\tTo_Char(public.git_commits.author_when, 'Day') AS day_of_week,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2, 3\nORDER BY time, count"
    }
   ]
  },
  {
   "title": "Net Changes by Repo",
   "type": "timeseries",
   "description": "Commit Additions - Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions - public.git_commit_stats.deletions) AS net_changes,\n\t'Total Net Changes' AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2, 3\nORDER BY 3"
    },
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions - public.git_commit_stats.deletions) AS net_changes,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2, 3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "Absolute Changes by Repo",
   "type": "timeseries",
   "description": "Commit Additions + Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions + public.git_commit_stats.deletions) AS absolute_changes,\n\t'Total Absolute Changes' AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2, 3\nORDER BY 3"
    },
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions + public.git_commit_stats.deletions) AS absolute_changes,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n\t$__timeGroup(public.git_commits.committer_when, '${interval}', 0) AS time\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2, 3\nORDER BY 3"
    }
   ]
  },
  { "title": "Net Changes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Net Changes by Repo",
   "type": "bargauge",
   "description": "Commit Additions - Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions - public.git_commit_stats.deletions) AS net_changes,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Net Changes by Author",
   "type": "bargauge",
   "description": "Commit Additions - Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT concat(public.git_commit_stats.repo_id,public.git_commit_stats.commit_hash)) AS commit_count,\n\tSUM(public.git_commit_stats.additions - public.git_commit_stats.deletions) AS net_changes,\n\tpublic.git_commits.author_name\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY public.git_commits.author_name\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Net Changes by Repo by File",
   "type": "bargauge",
   "description": "Commit Additions - Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions - public.git_commit_stats.deletions) AS net_changes,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n\tpublic.git_commit_stats.file_path\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY base_repository_name, file_path\nORDER BY 1 DESC"
    }
   ]
  },
  { "title": "Absolute Changes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Absolute Changes by Repo",
   "type": "bargauge",
   "description": "Commit Additions + Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions + public.git_commit_stats.deletions) AS net_changes,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY base_repository_name\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Absolute Changes by Author",
   "type": "bargauge",
   "description": "Commit Additions + Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT concat(public.git_commit_stats.repo_id,public.git_commit_stats.commit_hash)) AS commit_count,\n\tSUM(public.git_commit_stats.additions + public.git_commit_stats.deletions) AS net_changes,\n\tpublic.git_commits.author_name\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY public.git_commits.author_name\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Absolute Changes by Repo by File",
   "type": "bargauge",
   "description": "Commit Additions + Deletions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(public.git_commit_stats.additions + public.git_commit_stats.deletions) AS net_changes,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n\tpublic.git_commit_stats.file_path\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY base_repository_name, file_path\nORDER BY 1 DESC"
    }
   ]
  },
  { "title": "Day of Week", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Commits By Day of Week",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT concat(public.git_commit_stats.repo_id,public.git_commit_stats.commit_hash)) AS commit_count,\n\tTo_Char(public.git_commits.author_when, 'Day') AS day_of_week,\n\textract(dow from public.git_commits.author_when) AS day_of_week_num\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "Commits By Repo By Day of Week",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT concat(public.git_commit_stats.repo_id,public.git_commit_stats.commit_hash)) AS commit_count,\n\tpublic.github_repo_info.owner || '/' || public.github_repo_info.name AS base_repository_name,\n\tTo_Char(public.git_commits.author_when, 'Day') AS day_of_week,\n\textract(dow from public.git_commits.author_when) AS day_of_week_num\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2,3, 4\nORDER BY 2, 4"
    }
   ]
  },
  {
   "title": "Commits By Author By Day of Week",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT concat(public.git_commit_stats.repo_id,public.git_commit_stats.commit_hash)) AS commit_count,\n\tpublic.git_commits.author_name,\n\tTo_Char(public.git_commits.author_when, 'Day') AS day_of_week,\n\textract(dow from public.git_commits.author_when) AS day_of_week_num\nFROM public.git_commits\nINNER JOIN public.git_commit_stats ON public.git_commits.hash = public.git_commit_stats.commit_hash and public.git_commits.repo_id = public.git_commit_stats.repo_id\nINNER JOIN public.github_repo_info ON public.git_commits.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.git_commits.repo_id = public.repos.id\nWHERE public.git_commits.committer_when IS NOT NULL AND public.git_commits.parents < 2\nAND $__timeFilter(public.git_commits.committer_when) AND '${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 2,3,4\nORDER BY 2,4"
    }
   ]
  }
 ]
}