{
 "title": "TFSec Issues",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM tfsec_repo_issues"
    }
   ]
  },
  {
   "title": "Issues by Severity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(severity, 'UNKNOWN') AS severity, count(*) FROM tfsec_repo_issues\nGROUP BY severity\nORDER BY CASE\n    WHEN severity='CRITICAL' THEN 1\n    WHEN severity='HIGH' THEN 2\n    WHEN severity='MEDIUM' THEN 3\n    WHEN severity='LOW' THEN 4\n    ELSE 5\nEND\n"
    }
   ]
  },
  {
   "title": "All Issues",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT repo, rule_id, rule_description, rule_service, rule_provider, location_filename, resource, severity, resolution, description, impact FROM tfsec_repo_issues\nJOIN repos ON repos.id = tfsec_repo_issues.repo_id"
    }
   ]
  }
 ]
}