name: Lint SQL

on: [pull_request]

jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"
      - name: Install SQLFluff
        # TODO(patrickdevivo) consider updating this https://github.com/sqlfluff/sqlfluff/releases
        run: "pip install sqlfluff==1.3.2"
      - name: Reusable Lint SQL
        run: "sqlfluff lint"
